GET  http://localhost:3310/api/nursery

###

GET http://localhost:3310/api/children

###

POST http://localhost:3310/api/children HTTP/1.1
content-type: application/json

{
  "firstName" : "léon",
  "lastName" : "p",
  "birthdate" :"1997-10-22",
  "gender" : true,
  "allergies" : "oeuf",
  "parentId" : 2
}


###

GET  http://localhost:3310/api/userApp

###

GET http://localhost:3310/api/userLogin

###

POST http://localhost:3310/api/userLogin HTTP/1.1
content-type: application/json

{
  "first_name": "Léon",
  "last_name": "Patrick",
  "email": "leon.patrick@gmail.com",
  "user_password": "courgette"
}