GET  http://localhost:3310/api/nursery

###

GET  http://localhost:3310/api/userApp

###

POST http://localhost:3310/api/user/registration HTTP/1.1
content-type: application/json

{
  "firstName": "zozo",
  "lastName": "zozu",
  "email": "pouetj2@gmail.com",
  "password": "pouetMM!!56"
} 

###

POST http://localhost:3310/api/user/login HTTP/1.1
content-type: application/json

{
  "email": "pouet@gmail.com",
  "user_password": "pouet"
}

###

GET http://localhost:3310/api/user

