GET  http://localhost:3310/api/nursery

###

GET  http://localhost:3310/api/userApp

###

GET http://localhost:3310/api/userLogin

###

GET http://localhost:3310/api/children

###

POST http://localhost:3310/api/userLogin HTTP/1.1
content-type: application/json

{
  "firstName": "Léon",
  "lastName": "Patrick",
  "email": "leon.patrickdd@gmail.com",
  "password": "courgette!!MM55"
}